### ISSUE TITLE
将上游切换至 UOJ 官方版

### ISSUE THREAD

**Issue by skylee03** [zhzxdev/uoj-judger-standalone#3]
目前本项目基于 [UOJ 开源社区版](https://github.com/[UniversalOJ/UOJ-System) 修改，而 SOJ 则是基于 [UOJ 官方版](https://github.com/vfleaking/uoj)。两者评测器行为不完全一致，如：前者仅支持整数时限，而后者支持小数时限，这一差异将使得一些从 SOJ 导入的题目出现意料之外的 TLE。

将上游切换至 UOJ 官方版可更好地保证从 SOJ 导入的题目可以正常评测。

**Comment by thezzisu** [comment]
UOJ Official Upstream is now maintained as [premium](https://github.com/zhzxdev/uoj-judger-standalone/tree/premium) branch now after #4.
